import {
  Client,
  Invoice,
  Exception,
  DemoUser,
  ActivityItem,
  StatSparklineData,
  ChartData,
} from './types';

// Helper to generate a random UUID-like string for mock data
const generateId = (): string => Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);

// Helper to generate a date string in YYYY-MM-DD format within the last year
const generateDate = (daysAgo: number): string => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString().split('T')[0];
};

const generateDateTime = (minutesAgo: number): string => {
  const date = new Date();
  date.setMinutes(date.getMinutes() - minutesAgo);
  return date.toISOString();
};

export const DEMO_USER: DemoUser = {
  id: 'user-001',
  name: 'Sophia Miller',
  email: 'sophia.miller@example.com',
  role: 'Fractional CFO',
  plan: 'Professional',
  avatar: '/avatars/sophia.webp', // Assuming avatar path
  joinedAt: '2023-08-15',
};

export const MOCK_CLIENTS: Client[] = [
  {
    id: 'client-101',
    userId: DEMO_USER.id,
    name: 'Innovate Solutions Inc.',
    contactName: 'Liam Johnson',
    contactEmail: 'liam.johnson@innovatesolutions.com',
    status: 'active',
    createdAt: generateDateTime(3000),
    updatedAt: generateDateTime(120),
  },
  {
    id: 'client-102',
    userId: DEMO_USER.id,
    name: 'Global Ventures LLC',
    contactName: 'Olivia Davis',
    contactEmail: 'olivia.davis@globalventures.com',
    status: 'active',
    createdAt: generateDateTime(2800),
    updatedAt: generateDateTime(90),
  },
  {
    id: 'client-103',
    userId: DEMO_USER.id,
    name: 'FutureTech Corp',
    contactName: 'Noah Smith',
    contactEmail: 'noah.smith@futuretech.com',
    status: 'active',
    createdAt: generateDateTime(2500),
    updatedAt: generateDateTime(60),
  },
  {
    id: 'client-104',
    userId: DEMO_USER.id,
    name: 'Pioneer Brands Group',
    contactName: 'Emma Brown',
    contactEmail: 'emma.brown@pioneerbrands.com',
    status: 'inactive',
    createdAt: generateDateTime(2000),
    updatedAt: generateDateTime(100),
  },
  {
    id: 'client-105',
    userId: DEMO_USER.id,
    name: 'Velocity Digital Agency',
    contactName: 'Ava Wilson',
    contactEmail: 'ava.wilson@velocitydigital.com',
    status: 'active',
    createdAt: generateDateTime(1800),
    updatedAt: generateDateTime(30),
  },
  {
    id: 'client-106',
    userId: DEMO_USER.id,
    name: 'Apex Consultancies Ltd.',
    contactName: 'William Green',
    contactEmail: 'william.green@apexconsult.com',
    status: 'active',
    createdAt: generateDateTime(1500),
    updatedAt: generateDateTime(10),
  },
  {
    id: 'client-107',
    userId: DEMO_USER.id,
    name: 'BrightSpark Innovations',
    contactName: 'Isabella Taylor',
    contactEmail: 'isabella.taylor@brightspark.com',
    status: 'active',
    createdAt: generateDateTime(1300),
    updatedAt: generateDateTime(50),
  },
  {
    id: 'client-108',
    userId: DEMO_USER.id,
    name: 'Synergy Holdings Group',
    contactName: 'James Rodriguez',
    contactEmail: 'james.rodriquez@synergyholdings.com',
    status: 'active',
    createdAt: generateDateTime(1100),
    updatedAt: generateDateTime(20),
  },
  {
    id: 'client-109',
    userId: DEMO_USER.id,
    name: 'Quantum Logic Systems',
    contactName: 'Sophia Martinez',
    contactEmail: 'sophia.martinez@quantumlogic.com',
    status: 'active',
    createdAt: generateDateTime(900),
    updatedAt: generateDateTime(5),
  },
  {
    id: 'client-110',
    userId: DEMO_USER.id,
    name: 'Evergreen Enterprises',
    contactName: 'Benjamin Lee',
    contactEmail: 'benjamin.lee@evergreen.com',
    status: 'inactive',
    createdAt: generateDateTime(700),
    updatedAt: generateDateTime(15),
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'inv-001',
    userId: DEMO_USER.id,
    clientId: 'client-101',
    clientName: 'Innovate Solutions Inc.',
    invoiceNumber: 'INV-IS-2024-001',
    vendorName: 'Creative Marketing Agency',
    amount: 1250.75,
    currency: 'USD',
    issueDate: generateDate(45),
    dueDate: generateDate(15),
    description: 'Q1 Marketing Campaign Services',
    status: 'exception',
    createdAt: generateDateTime(460),
    updatedAt: generateDateTime(125),
  },
  {
    id: 'inv-002',
    userId: DEMO_USER.id,
    clientId: 'client-102',
    clientName: 'Global Ventures LLC',
    invoiceNumber: 'INV-GV-2024-002',
    vendorName: 'Cloud Hosting Solutions',
    amount: 540.00,
    currency: 'USD',
    issueDate: generateDate(30),
    dueDate: generateDate(0), // Due today
    description: 'Monthly Cloud Infrastructure Fees',
    status: 'overdue',
    createdAt: generateDateTime(350),
    updatedAt: generateDateTime(100),
  },
  {
    id: 'inv-003',
    userId: DEMO_USER.id,
    clientId: 'client-103',
    clientName: 'FutureTech Corp',
    invoiceNumber: 'INV-FT-2024-003',
    vendorName: 'Office Supplies Inc.',
    amount: 189.99,
    currency: 'USD',
    issueDate: generateDate(60),
    dueDate: generateDate(30),
    description: 'Office supplies order for March',
    status: 'paid',
    createdAt: generateDateTime(500),
    updatedAt: generateDateTime(200),
  },
  {
    id: 'inv-004',
    userId: DEMO_USER.id,
    clientId: 'client-101',
    clientName: 'Innovate Solutions Inc.',
    invoiceNumber: 'INV-IS-2024-002',
    vendorName: 'IT Support Services',
    amount: 3200.00,
    currency: 'USD',
    issueDate: generateDate(20),
    dueDate: generateDate(-10), // Due in 10 days
    description: 'Monthly IT maintenance contract',
    status: 'approved',
    createdAt: generateDateTime(280),
    updatedAt: generateDateTime(80),
  },
  {
    id: 'inv-005',
    userId: DEMO_USER.id,
    clientId: 'client-105',
    clientName: 'Velocity Digital Agency',
    invoiceNumber: 'INV-VD-2024-001',
    vendorName: 'Freelance Design Studio',
    amount: 750.00,
    currency: 'USD',
    issueDate: generateDate(10),
    dueDate: generateDate(-5), // Due in 5 days
    description: 'Website redesign project phase 1',
    status: 'exception',
    createdAt: generateDateTime(250),
    updatedAt: generateDateTime(50),
  },
  {
    id: 'inv-006',
    userId: DEMO_USER.id,
    clientId: 'client-102',
    clientName: 'Global Ventures LLC',
    invoiceNumber: 'INV-GV-2024-003',
    vendorName: 'Marketing Analytics Pro',
    amount: 899.50,
    currency: 'USD',
    issueDate: generateDate(50),
    dueDate: generateDate(20),
    description: 'Annual subscription for analytics software',
    status: 'approved',
    createdAt: generateDateTime(480),
    updatedAt: generateDateTime(210),
  },
  {
    id: 'inv-007',
    userId: DEMO_USER.id,
    clientId: 'client-106',
    clientName: 'Apex Consultancies Ltd.',
    invoiceNumber: 'INV-AC-2024-001',
    vendorName: 'Legal Advisory Group',
    amount: 4500.00,
    currency: 'USD',
    issueDate: generateDate(5),
    dueDate: generateDate(-25), // Due in 25 days
    description: 'Contract review services',
    status: 'pending_review',
    createdAt: generateDateTime(100),
    updatedAt: generateDateTime(10),
  },
  {
    id: 'inv-008',
    userId: DEMO_USER.id,
    clientId: 'client-107',
    clientName: 'BrightSpark Innovations',
    invoiceNumber: 'INV-BI-2024-001',
    vendorName: 'Hardware Solutions Co.',
    amount: 1500.00,
    currency: 'USD',
    issueDate: generateDate(25),
    dueDate: generateDate(-5), // Due in 5 days
    description: 'New workstation purchase',
    status: 'approved',
    createdAt: generateDateTime(300),
    updatedAt: generateDateTime(70),
  },
  {
    id: 'inv-009',
    userId: DEMO_USER.id,
    clientId: 'client-108',
    clientName: 'Synergy Holdings Group',
    invoiceNumber: 'INV-SH-2024-001',
    vendorName: 'Utility Services LLC',
    amount: 210.30,
    currency: 'USD',
    issueDate: generateDate(18),
    dueDate: generateDate(1),
    description: 'Monthly electricity bill',
    status: 'exception',
    createdAt: generateDateTime(200),
    updatedAt: generateDateTime(30),
  },
  {
    id: 'inv-010',
    userId: DEMO_USER.id,
    clientId: 'client-109',
    clientName: 'Quantum Logic Systems',
    invoiceNumber: 'INV-QL-2024-001',
    vendorName: 'Software Licensing Corp.',
    amount: 999.00,
    currency: 'USD',
    issueDate: generateDate(7),
    dueDate: generateDate(-23), // Due in 23 days
    description: 'Annual software license renewal',
    status: 'pending_review',
    createdAt: generateDateTime(150),
    updatedAt: generateDateTime(15),
  },
  {
    id: 'inv-011',
    userId: DEMO_USER.id,
    clientId: 'client-101',
    clientName: 'Innovate Solutions Inc.',
    invoiceNumber: 'INV-IS-2024-003',
    vendorName: 'Creative Marketing Agency',
    amount: 150.00,
    currency: 'USD',
    issueDate: generateDate(3),
    dueDate: generateDate(-27), // Due in 27 days
    description: 'Additional ad spend for April',
    status: 'pending_review',
    createdAt: generateDateTime(60),
    updatedAt: generateDateTime(5),
  },
  {
    id: 'inv-012',
    userId: DEMO_USER.id,
    clientId: 'client-102',
    clientName: 'Global Ventures LLC',
    invoiceNumber: 'INV-GV-2024-004',
    vendorName: 'Cloud Hosting Solutions',
    amount: 600.00,
    currency: 'USD',
    issueDate: generateDate(1),
    dueDate: generateDate(-29), // Due in 29 days
    description: 'Monthly Cloud Infrastructure Fees - April',
    status: 'pending_review',
    createdAt: generateDateTime(30),
    updatedAt: generateDateTime(2),
  },
];

export const MOCK_EXCEPTIONS: Exception[] = [
  {
    id: 'exc-001',
    userId: DEMO_USER.id,
    invoiceId: 'inv-001',
    invoiceNumber: 'INV-IS-2024-001',
    clientId: 'client-101',
    clientName: 'Innovate Solutions Inc.',
    type: 'missing_approval',
    description: 'Invoice exceeds $1000 threshold, requires CFO approval.',
    severity: 'high',
    status: 'open',
    assignedTo: DEMO_USER.name,
    createdAt: generateDateTime(120),
    updatedAt: generateDateTime(100),
  },
  {
    id: 'exc-002',
    userId: DEMO_USER.id,
    invoiceId: 'inv-002',
    invoiceNumber: 'INV-GV-2024-002',
    clientId: 'client-102',
    clientName: 'Global Ventures LLC',
    type: 'payment_risk',
    description: 'Invoice overdue by 5 days. Client has pending payments.',
    severity: 'critical',
    status: 'in_review',
    assignedTo: DEMO_USER.name,
    createdAt: generateDateTime(90),
    updatedAt: generateDateTime(10),
  },
  {
    id: 'exc-003',
    userId: DEMO_USER.id,
    invoiceId: 'inv-005',
    invoiceNumber: 'INV-VD-2024-001',
    clientId: 'client-105',
    clientName: 'Velocity Digital Agency',
    type: 'incorrect_amount',
    description: 'Amount ($750) differs from PO ($700). Investigation needed.',
    severity: 'medium',
    status: 'open',
    createdAt: generateDateTime(45),
    updatedAt: generateDateTime(40),
  },
  {
    id: 'exc-004',
    userId: DEMO_USER.id,
    invoiceId: 'inv-009',
    invoiceNumber: 'INV-SH-2024-001',
    clientId: 'client-108',
    clientName: 'Synergy Holdings Group',
    type: 'duplicate_invoice',
    description: 'Possible duplicate of INV-SH-2024-000 (check vendor portal).',
    severity: 'high',
    status: 'open',
    createdAt: generateDateTime(35),
    updatedAt: generateDateTime(30),
  },
  {
    id: 'exc-005',
    userId: DEMO_USER.id,
    invoiceId: 'inv-001', // Resolved instance for inv-001
    invoiceNumber: 'INV-IS-2024-001',
    clientId: 'client-101',
    clientName: 'Innovate Solutions Inc.',
    type: 'missing_approval',
    description: 'CFO approval obtained via email. Ready for processing.',
    severity: 'high',
    status: 'resolved',
    assignedTo: DEMO_USER.name,
    resolutionNotes: 'Approved by Liam Johnson (CFO) on 2024-04-10.',
    resolvedAt: generateDateTime(20),
    createdAt: generateDateTime(150),
    updatedAt: generateDateTime(20),
  },
  {
    id: 'exc-006',
    userId: DEMO_USER.id,
    invoiceId: 'inv-007',
    invoiceNumber: 'INV-AC-2024-001',
    clientId: 'client-106',
    clientName: 'Apex Consultancies Ltd.',
    type: 'missing_approval',
    description: 'Legal service invoice requires Senior Partner sign-off.',
    severity: 'high',
    status: 'open',
    createdAt: generateDateTime(15),
    updatedAt: generateDateTime(10),
  },
  {
    id: 'exc-007',
    userId: DEMO_USER.id,
    invoiceId: 'inv-004',
    invoiceNumber: 'INV-IS-2024-002',
    clientId: 'client-101',
    clientName: 'Innovate Solutions Inc.',
    type: 'wrong_vendor',
    description: 'Invoice from "IT Support Services" but usually from "Tech Solutions Pro". Confirm vendor change.',
    severity: 'medium',
    status: 'in_review',
    createdAt: generateDateTime(25),
    updatedAt: generateDateTime(5),
  },
  {
    id: 'exc-008',
    userId: DEMO_USER.id,
    invoiceId: 'inv-006',
    invoiceNumber: 'INV-GV-2024-003',
    clientId: 'client-102',
    clientName: 'Global Ventures LLC',
    type: 'other',
    description: 'Annual subscription renewal, check contract terms for auto-renewal clause.',
    severity: 'low',
    status: 'dismissed',
    resolutionNotes: 'Auto-renewal confirmed. Dismissed as non-exception.',
    resolvedAt: generateDateTime(12),
    createdAt: generateDateTime(80),
    updatedAt: generateDateTime(12),
  },
  {
    id: 'exc-009',
    userId: DEMO_USER.id,
    invoiceId: 'inv-010',
    invoiceNumber: 'INV-QL-2024-001',
    clientId: 'client-109',
    clientName: 'Quantum Logic Systems',
    type: 'missing_approval',
    description: 'Large software license renewal, needs department head approval.',
    severity: 'high',
    status: 'open',
    createdAt: generateDateTime(8),
    updatedAt: generateDateTime(2),
  },
  {
    id: 'exc-010',
    userId: DEMO_USER.id,
    invoiceId: 'inv-011',
    invoiceNumber: 'INV-IS-2024-003',
    clientId: 'client-101',
    clientName: 'Innovate Solutions Inc.',
    type: 'incorrect_amount',
    description: 'Additional ad spend requested ($150), but initial PO was for $100. Clarification required.',
    severity: 'medium',
    status: 'open',
    createdAt: generateDateTime(3),
    updatedAt: generateDateTime(1),
  },
];

export const STATS = {
  totalExceptions: '124',
  totalExceptionsGrowth: '+8%',
  openExceptions: 32,
  openExceptionsGrowth: '+15%',
  highPriorityOpen: 9,
  highPriorityOpenGrowth: '-5%',
  overdueExceptions: 3,
  overdueExceptionsGrowth: '+20%', // New overdue items
  avgResolutionTime: '3.2 days',
  avgResolutionTimeTrend: '-0.5 days', // Faster resolution
};

export const CHART_DATA: ChartData = {
  weeklyLabels: ['Week 1', 'Week 2', 'Week 3', 'Week 4', 'Week 5', 'Week 6', 'Week 7', 'Week 8', 'Week 9', 'Week 10', 'Week 11', 'Week 12'],
  exceptionsOpened: [18, 22, 19, 25, 21, 28, 24, 30, 26, 33, 29, 35],
  exceptionsResolved: [15, 20, 18, 22, 19, 25, 21, 27, 24, 30, 28, 32],
  exceptionsOverdue: [2, 3, 2, 4, 3, 5, 4, 6, 5, 7, 6, 8],
};

export const SPARKLINE_DATA: StatSparklineData = {
  totalExceptions: [85, 90, 88, 95, 92, 98, 105],
  openExceptions: [28, 30, 29, 32, 31, 35, 33],
  highPriorityOpen: [7, 8, 7, 9, 8, 10, 9],
  overdueExceptions: [1, 2, 2, 3, 2, 4, 3],
  resolutionTime: [3.5, 3.4, 3.2, 3.0, 3.1, 2.9, 2.8], // Average resolution time in days
};

export const RECENT_ACTIVITY: ActivityItem[] = [
  { id: generateId(), action: 'Added new invoice INV-QL-2024-001', user: DEMO_USER.name, avatar: 'SM', time: '2 minutes ago', type: 'create' },
  { id: generateId(), action: 'Created exception for INV-QL-2024-001', user: DEMO_USER.name, avatar: 'SM', time: '1 minute ago', type: 'exception' },
  { id: generateId(), action: 'Updated status of INV-GV-2024-002 to Overdue', user: DEMO_USER.name, avatar: 'SM', time: '1 hour ago', type: 'update' },
  { id: generateId(), action: 'Resolved exception for INV-IS-2024-001', user: DEMO_USER.name, avatar: 'SM', time: '3 hours ago', type: 'resolve' },
  { id: generateId(), action: 'Added new invoice INV-IS-2024-003', user: DEMO_USER.name, avatar: 'SM', time: '5 hours ago', type: 'create' },
  { id: generateId(), action: 'Created exception for INV-IS-2024-003', user: DEMO_USER.name, avatar: 'SM', time: '4 hours ago', type: 'exception' },
  { id: generateId(), action: 'Assigned exception EXC-002 to self', user: DEMO_USER.name, avatar: 'SM', time: '1 day ago', type: 'assign' },
  { id: generateId(), action: 'Dismissed exception for INV-GV-2024-003', user: DEMO_USER.name, avatar: 'SM', time: '2 days ago', type: 'dismiss' },
  { id: generateId(), action: 'Added new client Innovate Solutions Inc.', user: DEMO_USER.name, avatar: 'SM', time: '3 days ago', type: 'create' },
  { id: generateId(), action: 'Reviewed INV-AC-2024-001 for approval', user: DEMO_USER.name, avatar: 'SM', time: '4 days ago', type: 'update' },
  { id: generateId(), action: 'Created exception for INV-AC-2024-001', user: DEMO_USER.name, avatar: 'SM', time: '4 days ago', type: 'exception' },
  { id: generateId(), action: 'Approved INV-BI-2024-001 for payment', user: DEMO_USER.name, avatar: 'SM', time: '5 days ago', type: 'update' },
];

export function getById<T extends { id: string }>(arr: T[], id: string): T | undefined {
  return arr.find(x => x.id === id);
}